### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by CGYDSB** [Toytiny/milliFlow#11]
hi，Here are my results.
###The mean epe: 0.042125654944112224###
###The mean move_epe: 0.029855679418823913###
###The mean static_epe: 0.031009512409505134###
###The mean accs: 0.9660591990868477###
###The mean accr: 0.9857658201226146###
But it's very different from the results in your paper.
What's causing this? What can I do to improve it?
All:0.046
Moving: 0.051
Static: 0.009
Strict: 0.406 
Relax: 0.703

**Comment by Cdome559** [comment]
When I execute mian.py training, an error occurs

Traceback (most recent call last):
File "main.py", line 449, in
main()
File "main.py", line 440, in main
best_val_res = train(args, net, train_loader, val_loader,textio)
File "main.py", line 329, in train
total_loss, loss_items = train_one_epoch_seq(args, net, train_loader, opt)
File "/root/milliflow/clip_util.py", line 285, in train_one_epoch_seq
for i, data in tqdm(enumerate(train_loader), total=len(train_loader)):
File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in iter
for obj in iterable:
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 521, in next
data = self._next_data()
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
return self._process_data(data)
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
data.reraise()
File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 425, in reraise
raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
data = fetcher.fetch(index)
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/milliflow/dataset/dataset_clip.py", line 60, in getitem
return self.get_clip_item(index)
File "/root/milliflow/dataset/dataset_clip.py", line 134, in get_clip_item
pos_1, pos_2, feature_1, feature_2, labels, mask = self.get_sample_item(data,mini_sample)
TypeError: get_sample_item() takes 2 positional arguments but 3 were given

Please tell me what the problem is, thank you very much

**Comment by Toytiny** [comment]
This problem exists in our old version code and it has been fixed.
