### ISSUE TITLE
test

### ISSUE THREAD

**Issue by keroseus** [Toytiny/milliFlow#7]
Hi, when i try to test the trained model,it shows this question:
!Traceback (most recent call last):
  File "main.py", line 449, in <module>
    main()
  File "main.py", line 432, in main
    test(args, net, test_loader,textio)
  File "main.py", line 170, in test
    sf_metric, epe_xyz = test_one_epoch_seq(args, net, test_loader, textio)
  File "/root/milliflow/clip_util.py", line 456, in test_one_epoch_seq
    pred_f, gfeat = net(pc1, pc2, ft1, ft2, gfeat)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/milliflow/models/mmflow_t.py", line 132, in forward
    final_features, gfeat = self.Backbone(pc1,pc2,feature1,feature2, gfeat_prev)
  File "/root/milliflow/models/mmflow_t.py", line 104, in Backbone
    cor_features = self.fc_layer(pc1, pc2, pc1_features, pc2_features)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/milliflow/utils/model_utils/radarflow_util.py", line 207, in forward
    knn_idx = knn_point(self.nsample, xyz2, xyz1) # B, N1, nsample
  File "/root/milliflow/utils/model_utils/radarflow_util.py", line 98, in knn_point
    _, group_idx = torch.topk(sqrdists, nsample, dim = -1, largest=False, sorted=True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26
It seems like nsample is out of number of distances?

**Comment by Toytiny** [comment]
please try to download our latest version of dataset for experiments.
