### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by keroseus** [Toytiny/milliFlow#8]
Still can not solve it ,help!
Traceback (most recent call last):
  File "main.py", line 449, in <module>
    main()
  File "main.py", line 412, in main
    train_set = dataset_dict[args.dataset](args=args, root = args.dataset_path, partition=args.train_set,textio=textio)
  File "/root/milliflow/dataset/dataset_clip.py", line 31, in __init__
    samples = sorted(os.listdir(clip_path), key=lambda x: eval(x.split("_")[-1].split("-")[-1].split(".")[0]))
  File "/root/milliflow/dataset/dataset_clip.py", line 31, in <lambda>
    samples = sorted(os.listdir(clip_path), key=lambda x: eval(x.split("_")[-1].split("-")[-1].split(".")[0]))
  File "<string>", line 1, in <module>
NameError: name 'checkpoints' is not defined

**Comment by CGYDSB** [comment]
If you are using Jupyter Notebook, it might have automatically generated .ipynb_checkpoints to store checkpoints of the notebook (.ipynb files). You can simply delete it directly from the folder using the command.
